#spring.application.name=spring-security-one
spring:
  application:
    name: spring-security-one

#  security:
#    user: # Basic authentication with single static user
#      name: admin
#      password: admin@1234

